### ISSUE TITLE
Call to unknown reset method in htmok script

### ISSUE THREAD

**Issue by sflitman** [benkasminbullock/html-valid#15]
Can't locate object method "reset" via package "HTML::Valid" at /usr/local/bin/htmlok line 69.

**Comment by benkasminbullock** [comment]
The function "reset" was commented out in Valid.xs. I uncommented it but this caused a chain of problems. The best option remaining is to remove it from the htmlok script. I'm not sure what it did, but it had long since been switched off, and the relevant data structures within the tidy library have changed completely since then, so if it was something necessary it will have to be reimplemented.

**Comment by sflitman** [comment]
htmlok works fine with line 69 commented out
