### ISSUE TITLE
Undeclared dependency Data::Validate::URI?

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/html-valid#9]
On some smoker machines the t/script.t test fails like this:

```
#   Failed test 'got no output running on empty file'
#   at t/script.t line 17.
# Looks like you failed 1 test of 2.
t/script.t ......
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
```

Looking at the strace log of the test run it seems that Data::Validate::URI is missing.

**Comment by benkasminbullock** [comment]
It should be testing whether that exists and only running a certain request if so, so I think there is some error in my script.

**Comment by benkasminbullock** [comment]
This problem with tests failing was due to leaving a statement

```
 print "$@\n";
```

in the code after the 

```
eval {
     require Data::Validate::URI;
};
```

line and then running a test that the script did not produce output when run on a non-existent input file. Obviously this produced output if the user did not have Data::Validate::URI regardless of whether the file did not exist, so the test was failing. I've solved this problem by removing the print statement:

https://github.com/benkasminbullock/html-valid/commit/1c6d6a1a1d9ecdb2ebdef1301db0d64236e1b004#diff-ef39764e54a7be0be98aac744066f57bL23

I believe this is OK since version 0.02_02 did not have any of these errors in its testing.

http://matrix.cpantesters.org/?dist=HTML-Valid+0.02_02

The one failed test there is due to a compilation problem, kept here as an issue:

https://github.com/benkasminbullock/html-valid/issues/10

Thank you again for your reports, I very much appreciate them.
